#!/usr/bin/env node
import assert from 'node:assert/strict';
import { execFileSync, spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { beginInstallationTransaction, completeInstallationTransaction, getPriorSelection, verifyRegistryArtifact } from '../../ois/bin/verified-plugin-install.mjs';
const repo=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const read=(p)=>JSON.parse(readFileSync(join(repo,p),'utf8'));
const sha=(p)=>createHash('sha256').update(readFileSync(p)).digest('hex');
const run=(bin,args,cwd=repo,env=process.env)=>execFileSync(bin,args,{cwd,env,encoding:'utf8',stdio:['ignore','pipe','pipe']});
const env={...process.env,OIS_BUILD_SHA:process.env.OIS_BUILD_SHA||'1055d80161df4d36e6a1876676a822e7fe99b029',OIS_BUILD_TREE:process.env.OIS_BUILD_TREE||'92d885cb7adc7696fa768f707141232b0cce511c',OIS_BUILD_DIRTY:'false',OIS_ALLOW_DIRTY_BUILD:process.env.CI?'0':'1',SOURCE_DATE_EPOCH:process.env.SOURCE_DATE_EPOCH||'0'};
const mutations=[]; const kill=(name,fn)=>{assert.throws(fn,undefined,`mutation survived: ${name}`);mutations.push(name)};
function validatePkg(p,kind){assert.deepEqual(p.dependencies||{},{});for(const h of ['preinstall','install','postinstall','prepack'])assert.equal(p.scripts?.[h],undefined);if(kind==='pi')assert.deepEqual(p.peerDependencies,{'@earendil-works/pi-tui':'0.81.1',typebox:'1.1.38'});else assert.deepEqual(p.peerDependencies||{},{});}
function validateIdentity(i,p){assert.match(i.sourceCommit,/^[0-9a-f]{40}$/);assert.match(i.sourceTree,/^[0-9a-f]{40}$/);assert.equal(i.dirty,false);assert.equal(i.packageVersion,p.version);assert.equal(i.buildTime,new Date(Number(env.SOURCE_DATE_EPOCH)*1000).toISOString());assert.equal(i.bundlerVersion,'0.28.0');assert.equal(i.target,'node24');assert.equal(i.splitting,false)}
function validateMeta(m,kind){const outputs=Object.keys(m.outputs);assert.equal(outputs.filter(x=>x.endsWith('.js')).length,2);const ext=[...new Set(outputs.flatMap(x=>(m.outputs[x].imports||[]).filter(i=>i.external&&!i.path.startsWith('node:')).map(i=>i.path)))].sort();assert.deepEqual(ext,kind==='pi'?['@earendil-works/pi-tui','typebox']:[])}
function validateMembers(root){const m=JSON.parse(readFileSync(join(root,'dist/member-manifest.json')));for(const x of m.files){const p=join(root,x.path);assert.ok(existsSync(p));assert.equal(readFileSync(p).length,x.size);assert.equal(sha(p),x.sha256)}return m}
for(const kind of ['claude','pi']) run(process.execPath,['scripts/build/build-self-contained-plugin.mjs',kind],repo,env);
const baseline={};
for(const kind of ['claude','pi']){const root=join(repo,'adapters',`${kind}-plugin`),p=JSON.parse(readFileSync(join(root,'package.json'))),i=JSON.parse(readFileSync(join(root,'dist/identity.json'))),m=JSON.parse(readFileSync(join(root,'dist/metafile.json')));validatePkg(p,kind);validateIdentity(i,p);validateMeta(m,kind);validateMembers(root);baseline[kind]={bundle:sha(join(root,'dist',kind==='claude'?'shim.js':'index.js')),seed:sha(join(root,'dist/seed-skills.js')),meta:sha(join(root,'dist/metafile.json')),members:sha(join(root,'dist/member-manifest.json'))}}
for(const kind of ['claude','pi']) run(process.execPath,['scripts/build/build-self-contained-plugin.mjs',kind],repo,env);
for(const kind of ['claude','pi']){const root=join(repo,'adapters',`${kind}-plugin`);assert.deepEqual({bundle:sha(join(root,'dist',kind==='claude'?'shim.js':'index.js')),seed:sha(join(root,'dist/seed-skills.js')),meta:sha(join(root,'dist/metafile.json')),members:sha(join(root,'dist/member-manifest.json'))},baseline[kind],`${kind} repeat build drift`)}
const td=mkdtempSync(join(os.tmpdir(),'minimal-aligned-'));
try{
  const packed={};
  for(const kind of ['claude','pi']){const src=join(repo,'adapters',`${kind}-plugin`),a=join(td,`${kind}-a`),b=join(td,`${kind}-b`);cpSync(src,a,{recursive:true,filter:p=>!p.includes('/node_modules')&&!p.includes('/test')&&!p.includes('/src')});cpSync(src,b,{recursive:true,filter:p=>!p.includes('/node_modules')&&!p.includes('/test')&&!p.includes('/src')});const pa=JSON.parse(run('npm',['pack','--ignore-scripts','--json'],a))[0],pb=JSON.parse(run('npm',['pack','--ignore-scripts','--json'],b))[0];assert.equal(pa.integrity,pb.integrity,`${kind} two-root npm pack drift`);const tgz=join(a,pa.filename),prefix=join(td,`${kind}-install`);packed[kind]={tgz,integrity:pa.integrity,manifest:join(a,'package.json')};run('npm',['install',tgz,`--prefix=${prefix}`,'--ignore-scripts','--no-audit','--no-fund','--omit=dev','--legacy-peer-deps']);const lock=JSON.parse(readFileSync(join(prefix,'package-lock.json')));assert.equal(Object.keys(lock.packages).length,2,`${kind} consumer closure floated`);validateMembers(join(prefix,'node_modules','@apnex',`${kind}-plugin`));}
  const registry=spawn(process.execPath,[join(repo,'scripts/test/fixtures/read-only-npm-registry.mjs'),'@apnex/pi-plugin','0.1.9',packed.pi.tgz,packed.pi.manifest],{stdio:['ignore','pipe','inherit']});
  const port=await new Promise((resolvePort,reject)=>{let s='';registry.stdout.on('data',b=>{s+=b;if(s.includes('\n'))resolvePort(s.trim())});registry.on('error',reject);registry.on('exit',c=>c&&reject(new Error(`registry exited ${c}`)))});
  let verifiedArtifact;
  try { const npmCli=join(run('npm',['root','-g']).trim(),'npm/bin/npm-cli.js'),avrState=join(td,'avr-state');const verified=verifyRegistryArtifact({name:'@apnex/pi-plugin',version:'0.1.9',expectedIntegrity:packed.pi.integrity,publicationAttestation:'attest:test',stateRoot:avrState,registry:`http://127.0.0.1:${port}/`,npmCli});verifiedArtifact=verified;assert.ok(existsSync(verified.verificationPath));assert.equal(verified.avr.distIntegrity,packed.pi.integrity);const reused=verifyRegistryArtifact({name:'@apnex/pi-plugin',version:'0.1.9',expectedIntegrity:packed.pi.integrity,publicationAttestation:'attest:test',stateRoot:avrState,registry:`http://127.0.0.1:${port}/`,npmCli});assert.equal(reused.reused,true);kill('wrong-registry-integrity',()=>verifyRegistryArtifact({name:'@apnex/pi-plugin',version:'0.1.9',expectedIntegrity:'sha512-'+Buffer.alloc(64).toString('base64'),publicationAttestation:'attest:test',stateRoot:join(td,'bad-avr'),registry:`http://127.0.0.1:${port}/`,npmCli})); } finally { registry.kill('SIGTERM'); }
  const state=join(td,'state'),root=verifiedArtifact.root,avr=verifiedArtifact.verificationPath;const t1=beginInstallationTransaction({stateRoot:state,seatId:'seat-a',harness:'pi',avrPath:avr,root});const c1=completeInstallationTransaction({stateRoot:state,seatId:'seat-a',harness:'pi',outcome:'installed',observation:{entry:'x'}});const t2=beginInstallationTransaction({stateRoot:state,seatId:'seat-a',harness:'pi',avrPath:avr,root});assert.notEqual(t1.pending.id,t2.pending.id);const c2=completeInstallationTransaction({stateRoot:state,seatId:'seat-a',harness:'pi',outcome:'installed'});assert.notEqual(c1.receiptPath,c2.receiptPath);assert.equal(getPriorSelection({stateRoot:state,seatId:'seat-a',harness:'pi'}).priorReceipt.id,c1.receipt.id);beginInstallationTransaction({stateRoot:state,seatId:'seat-b',harness:'pi',avrPath:avr,root});kill('duplicate-pending',()=>beginInstallationTransaction({stateRoot:state,seatId:'seat-b',harness:'pi',avrPath:avr,root}));completeInstallationTransaction({stateRoot:state,seatId:'seat-b',harness:'pi',outcome:'failed'});const rootPkg=join(root,'package.json'),saved=readFileSync(rootPkg);await import('node:fs').then(({chmodSync})=>chmodSync(rootPkg,0o644));writeFileSync(rootPkg,`${saved.toString()} `);kill('root-replaced-after-verify',()=>beginInstallationTransaction({stateRoot:state,seatId:'seat-c',harness:'pi',avrPath:avr,root}));
}finally{rmSync(td,{recursive:true,force:true})}
const cp=read('adapters/claude-plugin/package.json'),pp=read('adapters/pi-plugin/package.json'),ci=read('adapters/claude-plugin/dist/identity.json'),pi=read('adapters/pi-plugin/dist/identity.json'),cm=read('adapters/claude-plugin/dist/metafile.json'),pm=read('adapters/pi-plugin/dist/metafile.json');
for(const [n,mut,k] of [['claude-dependency',{...cp,dependencies:{x:'^1'}},'claude'],['pi-dependency',{...pp,dependencies:{x:'1'}},'pi'],['install-script',{...cp,scripts:{...cp.scripts,install:'evil'}},'claude'],['postinstall-script',{...pp,scripts:{...pp.scripts,postinstall:'evil'}},'pi'],['pi-floating-peer',{...pp,peerDependencies:{...pp.peerDependencies,typebox:'*'}},'pi'],['pi-extra-peer',{...pp,peerDependencies:{...pp.peerDependencies,evil:'1'}},'pi']])kill(n,()=>validatePkg(mut,k));
for(const [n,mut,p] of [['short-sha',{...ci,sourceCommit:'1055d801'},cp],['dirty',{...ci,dirty:true},cp],['wrong-version',{...ci,packageVersion:'0.0.0'},cp],['wall-clock',{...ci,buildTime:'2026-01-01T00:00:00Z'},cp],['moving-bundler',{...ci,bundlerVersion:'latest'},cp],['wrong-target',{...pi,target:'node22'},pp],['splitting',{...pi,splitting:true},pp],['wrong-tree',{...pi,sourceTree:'bad'},pp]])kill(n,()=>validateIdentity(mut,p));
const addExternal=(m,path)=>{const x=structuredClone(m),k=Object.keys(x.outputs).find(k=>k.endsWith('.js'));x.outputs[k].imports.push({path,kind:'import-statement',external:true});return x};
kill('claude-bare-external',()=>validateMeta(addExternal(cm,'left-pad'),'claude'));kill('pi-bare-external',()=>validateMeta(addExternal(pm,'left-pad'),'pi'));kill('pi-registry-host-peer',()=>validateMeta(addExternal(pm,'@earendil-works/pi-coding-agent'),'pi'));
const ois=readFileSync(join(repo,'ois/bin/ois'),'utf8'),pc=read('config/harnesses/pi.json'),cc=read('config/harnesses/claude.json');assert.ok(!ois.includes('npm install -g "@apnex/network-adapter@latest"'));assert.ok(ois.includes('PI_PLUGIN_SPEC override is forbidden'));assert.ok(ois.indexOf('node "$na_bin" "$cdir/skills"') < ois.indexOf('claude plugin marketplace add "$mp"'),'Claude must seed before native actuation');assert.deepEqual(pc.piSettings.packages,[]);assert.equal(pc.piPluginSpec,'@apnex/pi-plugin@0.1.9');assert.equal(cc.pluginVersion,'0.1.18');
for(const [n,text] of [['global-latest-seed','npm install -g "@apnex/network-adapter@latest"'],['pi-native-npm','npm:@apnex/pi-plugin@0.1.9'],['override-trust','${PI_PLUGIN_SPEC:-$pspec}'],['companion-package','npm:pi-web-access'],['runtime-supervisor','supervisor detects'],['tgz-escrow','frozen-tgz escrow']])kill(n,()=>{const mutated=ois+JSON.stringify(pc)+text;assert.ok(!mutated.includes(text))});
const installer=readFileSync(join(repo,'ois/bin/verified-plugin-install.mjs'),'utf8');for(const token of ['--ignore-scripts','create-once mismatch','selection CAS mismatch','publication attestation required','realized closure contains consumer runtime packages','unsafe tar member'])assert.ok(installer.includes(token));
for(const [n,token] of [['missing-ignore-scripts','--ignore-scripts'],['missing-cas','selection CAS mismatch'],['missing-attestation','publication attestation required'],['missing-closure-gate','realized closure contains consumer runtime packages'],['missing-tar-gate','unsafe tar member']])kill(n,()=>assert.ok(installer.replaceAll(token,'').includes(token)));
console.log(JSON.stringify({pass:true,gates:['G01','G02','G03','G04','G05','G06','G07','G08','G09','G10','G11','G12','G13','G14','G15','G16','G17','G18'],mutationsKilled:mutations.length,mutations,baseline},null,2));
